//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NamoBuddhaya.test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Biz_PasswordHistory
    {
        public long Id { get; set; }
        public string Status { get; set; }
        public string User_Name { get; set; }
        public string Old_Password { get; set; }
        public string New_Password { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<long> ChangedByUser { get; set; }
        public string ChangedByTerminalId { get; set; }
        public System.DateTime sys_DateCreation { get; set; }
        public System.DateTime sys_DateLastModification { get; set; }
        public Nullable<long> IdStakeholder { get; set; }
    
        public virtual Biz_Stakeholder Biz_Stakeholder { get; set; }
    }
}
