//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NamoBuddhaya.test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Biz_SlabDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Biz_SlabDetail()
        {
            this.Biz_SlabValueDetail = new HashSet<Biz_SlabValueDetail>();
        }
    
        public long Id { get; set; }
        public Nullable<long> IdSlab { get; set; }
        public Nullable<decimal> Slab_From { get; set; }
        public Nullable<decimal> Slab_To { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<decimal> Rate { get; set; }
    
        public virtual Biz_Slab Biz_Slab { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Biz_SlabValueDetail> Biz_SlabValueDetail { get; set; }
    }
}
