//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NamoBuddhaya.test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Biz_SalesAgent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Biz_SalesAgent()
        {
            this.Biz_BranchSalesAgent = new HashSet<Biz_BranchSalesAgent>();
        }
    
        public long Id { get; set; }
        public long IdStakeholder { get; set; }
        public string Marital_Status { get; set; }
        public string EPF_No { get; set; }
        public string ETF_No { get; set; }
        public Nullable<long> IdCurrentBranch { get; set; }
        public Nullable<long> IdRelatedBranch { get; set; }
        public Nullable<long> IdCurrentPosition { get; set; }
        public Nullable<long> IdCurrentDesignation { get; set; }
        public Nullable<long> IdReportingEmployee { get; set; }
        public Nullable<System.DateTime> DateJoined { get; set; }
        public Nullable<System.DateTime> DateConfirmed { get; set; }
        public Nullable<System.DateTime> DateResigned { get; set; }
        public Nullable<long> IdStatus { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Biz_BranchSalesAgent> Biz_BranchSalesAgent { get; set; }
    }
}
