//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NamoBuddhaya.test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Biz_SecurityGroupScreen
    {
        public long Id { get; set; }
        public long IdModule { get; set; }
        public long IdScreen { get; set; }
        public long IdSecurityGroup { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    
        public virtual Biz_Screen Biz_Screen { get; set; }
        public virtual Biz_SecurityGroup Biz_SecurityGroup { get; set; }
        public virtual Biz_SystemModule Biz_SystemModule { get; set; }
    }
}
