//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NamoBuddhaya.test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Biz_SalesBudgetDetail
    {
        public long Id { get; set; }
        public Nullable<long> IdProduct { get; set; }
        public Nullable<long> IdUnitOfMeasure { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Value { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> IdBranch { get; set; }
        public Nullable<long> IdSalesBudget { get; set; }
    
        public virtual Biz_Branch Biz_Branch { get; set; }
        public virtual Biz_Product Biz_Product { get; set; }
        public virtual Biz_SalesBudget Biz_SalesBudget { get; set; }
    }
}
