//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NamoBuddhaya.test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Biz_InventoryItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Biz_InventoryItem()
        {
            this.Biz_Invoice = new HashSet<Biz_Invoice>();
            this.Biz_SalesTargetDetail = new HashSet<Biz_SalesTargetDetail>();
        }
    
        public long Id { get; set; }
        public string CodeInventoryItem { get; set; }
        public long IdBranchproduct { get; set; }
        public string Status { get; set; }
        public long IdBranch { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> IdProduct { get; set; }
        public string Description { get; set; }
    
        public virtual Biz_Branch Biz_Branch { get; set; }
        public virtual Biz_BranchProduct Biz_BranchProduct { get; set; }
        public virtual Biz_Product Biz_Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Biz_Invoice> Biz_Invoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Biz_SalesTargetDetail> Biz_SalesTargetDetail { get; set; }
    }
}
