//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NamoBuddhaya.test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Biz_PriceBookDetail
    {
        public long Id { get; set; }
        public Nullable<long> IdPriceBook { get; set; }
        public Nullable<decimal> Discount_Rate { get; set; }
        public Nullable<decimal> PricePer_Unit { get; set; }
        public Nullable<decimal> CostPer_Unit { get; set; }
        public Nullable<decimal> Commission_Rate { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> IdProduct { get; set; }
        public Nullable<long> IdUnitOfMeasure { get; set; }
    
        public virtual Biz_Product Biz_Product { get; set; }
        public virtual Biz_UnitOfMeasure Biz_UnitOfMeasure { get; set; }
    }
}
