//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NamoBuddhaya.test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Biz_BranchProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Biz_BranchProduct()
        {
            this.Biz_InventoryItem = new HashSet<Biz_InventoryItem>();
            this.Biz_Invoice = new HashSet<Biz_Invoice>();
        }
    
        public long Id { get; set; }
        public long IdBranch { get; set; }
        public long IdProduct { get; set; }
        public Nullable<decimal> StockOpen { get; set; }
        public Nullable<decimal> StockOnOrder { get; set; }
        public Nullable<decimal> Present_Value { get; set; }
        public Nullable<decimal> Present_Stock { get; set; }
        public Nullable<decimal> Reorder_Level { get; set; }
        public Nullable<decimal> Reorder_Quantity { get; set; }
        public Nullable<decimal> Buffer_Stock { get; set; }
        public string Auth_Status { get; set; }
        public Nullable<decimal> Reserve_Quantity { get; set; }
        public long IdProductCategory { get; set; }
        public long IdSubProductCategory { get; set; }
    
        public virtual Biz_Branch Biz_Branch { get; set; }
        public virtual Biz_Product Biz_Product { get; set; }
        public virtual Biz_ProductCategory Biz_ProductCategory { get; set; }
        public virtual Biz_SubProductCategory Biz_SubProductCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Biz_InventoryItem> Biz_InventoryItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Biz_Invoice> Biz_Invoice { get; set; }
    }
}
