//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NamoBuddhaya.test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Biz_StakeholderType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Biz_StakeholderType()
        {
            this.Biz_Stakeholder = new HashSet<Biz_Stakeholder>();
            this.Biz_StakeholderSecurityGroup = new HashSet<Biz_StakeholderSecurityGroup>();
            this.Biz_StakeholderTypeSecurityGroup = new HashSet<Biz_StakeholderTypeSecurityGroup>();
            this.Biz_StakeholderTypeStakeholder = new HashSet<Biz_StakeholderTypeStakeholder>();
        }
    
        public long Id { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Biz_Stakeholder> Biz_Stakeholder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Biz_StakeholderSecurityGroup> Biz_StakeholderSecurityGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Biz_StakeholderTypeSecurityGroup> Biz_StakeholderTypeSecurityGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Biz_StakeholderTypeStakeholder> Biz_StakeholderTypeStakeholder { get; set; }
    }
}
