//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NamoBuddhaya.test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Biz_Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Biz_Invoice()
        {
            this.Biz_MemberCommssionDetail = new HashSet<Biz_MemberCommssionDetail>();
        }
    
        public long Id { get; set; }
        public Nullable<long> IdSalesTransaction { get; set; }
        public Nullable<long> IdSalesTarget { get; set; }
        public Nullable<long> IdBranchPriceBook { get; set; }
        public Nullable<decimal> Discount_Value { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Total_Value { get; set; }
        public Nullable<decimal> Commission_Value { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<long> IdBranchProduct { get; set; }
        public long IdSalesPerson { get; set; }
        public string Status { get; set; }
        public int serialNo { get; set; }
        public long IdItem { get; set; }
        public Nullable<long> IdUnitOfMeasure { get; set; }
        public Nullable<long> IdBranch { get; set; }
    
        public virtual Biz_Branch Biz_Branch { get; set; }
        public virtual Biz_BranchPriceBook Biz_BranchPriceBook { get; set; }
        public virtual Biz_BranchProduct Biz_BranchProduct { get; set; }
        public virtual Biz_InventoryItem Biz_InventoryItem { get; set; }
        public virtual Biz_SalesTarget Biz_SalesTarget { get; set; }
        public virtual Biz_SalesTransaction Biz_SalesTransaction { get; set; }
        public virtual Biz_UnitOfMeasure Biz_UnitOfMeasure { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Biz_MemberCommssionDetail> Biz_MemberCommssionDetail { get; set; }
    }
}
