//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NamoBuddhaya.test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Biz_Branch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Biz_Branch()
        {
            this.Biz_BranchPriceBook = new HashSet<Biz_BranchPriceBook>();
            this.Biz_BranchProduct = new HashSet<Biz_BranchProduct>();
            this.Biz_BranchSalesAgent = new HashSet<Biz_BranchSalesAgent>();
            this.Biz_InventoryItem = new HashSet<Biz_InventoryItem>();
            this.Biz_Invoice = new HashSet<Biz_Invoice>();
            this.Biz_MemberCommssionDetail = new HashSet<Biz_MemberCommssionDetail>();
            this.Biz_MemberSalesAgentPosition = new HashSet<Biz_MemberSalesAgentPosition>();
            this.Biz_MemberSalesTarget = new HashSet<Biz_MemberSalesTarget>();
            this.Biz_SalesBudgetDetail = new HashSet<Biz_SalesBudgetDetail>();
            this.Biz_SalesTargetDetail = new HashSet<Biz_SalesTargetDetail>();
            this.Biz_SalesTransaction = new HashSet<Biz_SalesTransaction>();
            this.Biz_StakeholderBranch = new HashSet<Biz_StakeholderBranch>();
        }
    
        public long Id { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Biz_BranchPriceBook> Biz_BranchPriceBook { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Biz_BranchProduct> Biz_BranchProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Biz_BranchSalesAgent> Biz_BranchSalesAgent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Biz_InventoryItem> Biz_InventoryItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Biz_Invoice> Biz_Invoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Biz_MemberCommssionDetail> Biz_MemberCommssionDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Biz_MemberSalesAgentPosition> Biz_MemberSalesAgentPosition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Biz_MemberSalesTarget> Biz_MemberSalesTarget { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Biz_SalesBudgetDetail> Biz_SalesBudgetDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Biz_SalesTargetDetail> Biz_SalesTargetDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Biz_SalesTransaction> Biz_SalesTransaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Biz_StakeholderBranch> Biz_StakeholderBranch { get; set; }
    }
}
