//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NamoBuddhaya.test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Biz_MemberCommssionDetail
    {
        public long Id { get; set; }
        public Nullable<long> IdSalesAgent { get; set; }
        public Nullable<long> IdSalesTransaction { get; set; }
        public Nullable<decimal> Commission { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<decimal> Target_Commission { get; set; }
        public Nullable<decimal> Total_Commission { get; set; }
        public Nullable<System.DateTime> Date_Commission { get; set; }
        public Nullable<long> IdBranch { get; set; }
        public Nullable<long> SequenceNumber { get; set; }
        public Nullable<long> IdInvoice { get; set; }
    
        public virtual Biz_Branch Biz_Branch { get; set; }
        public virtual Biz_Invoice Biz_Invoice { get; set; }
        public virtual Biz_SalesTransaction Biz_SalesTransaction { get; set; }
        public virtual Biz_Stakeholder Biz_Stakeholder { get; set; }
    }
}
