//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NamoBuddhaya.test
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BizFlexerDBEntities : DbContext
    {
        public BizFlexerDBEntities()
            : base("name=BizFlexerDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Biz_Branch> Biz_Branch { get; set; }
        public virtual DbSet<Biz_BranchPriceBook> Biz_BranchPriceBook { get; set; }
        public virtual DbSet<Biz_BranchProduct> Biz_BranchProduct { get; set; }
        public virtual DbSet<Biz_BranchSalesAgent> Biz_BranchSalesAgent { get; set; }
        public virtual DbSet<Biz_Commission> Biz_Commission { get; set; }
        public virtual DbSet<Biz_Currency> Biz_Currency { get; set; }
        public virtual DbSet<Biz_InventoryItem> Biz_InventoryItem { get; set; }
        public virtual DbSet<Biz_Invoice> Biz_Invoice { get; set; }
        public virtual DbSet<Biz_MemberCommssionDetail> Biz_MemberCommssionDetail { get; set; }
        public virtual DbSet<Biz_MemberSalesAgentPosition> Biz_MemberSalesAgentPosition { get; set; }
        public virtual DbSet<Biz_MemberSalesTarget> Biz_MemberSalesTarget { get; set; }
        public virtual DbSet<Biz_MultipleRate> Biz_MultipleRate { get; set; }
        public virtual DbSet<Biz_PasswordHistory> Biz_PasswordHistory { get; set; }
        public virtual DbSet<Biz_Period> Biz_Period { get; set; }
        public virtual DbSet<Biz_PriceBook> Biz_PriceBook { get; set; }
        public virtual DbSet<Biz_PriceBookDetail> Biz_PriceBookDetail { get; set; }
        public virtual DbSet<Biz_Product> Biz_Product { get; set; }
        public virtual DbSet<Biz_ProductCategory> Biz_ProductCategory { get; set; }
        public virtual DbSet<Biz_SalesAgent> Biz_SalesAgent { get; set; }
        public virtual DbSet<Biz_SalesAgentPosition> Biz_SalesAgentPosition { get; set; }
        public virtual DbSet<Biz_SalesBudget> Biz_SalesBudget { get; set; }
        public virtual DbSet<Biz_SalesBudgetDetail> Biz_SalesBudgetDetail { get; set; }
        public virtual DbSet<Biz_SalesForecast> Biz_SalesForecast { get; set; }
        public virtual DbSet<Biz_SalesForecastDetail> Biz_SalesForecastDetail { get; set; }
        public virtual DbSet<Biz_SalesTarget> Biz_SalesTarget { get; set; }
        public virtual DbSet<Biz_SalesTargetDetail> Biz_SalesTargetDetail { get; set; }
        public virtual DbSet<Biz_SalesTransaction> Biz_SalesTransaction { get; set; }
        public virtual DbSet<Biz_Screen> Biz_Screen { get; set; }
        public virtual DbSet<Biz_SecurityGroup> Biz_SecurityGroup { get; set; }
        public virtual DbSet<Biz_SecurityGroupScreen> Biz_SecurityGroupScreen { get; set; }
        public virtual DbSet<Biz_Serial> Biz_Serial { get; set; }
        public virtual DbSet<Biz_SingleRate> Biz_SingleRate { get; set; }
        public virtual DbSet<Biz_Slab> Biz_Slab { get; set; }
        public virtual DbSet<Biz_SlabDetail> Biz_SlabDetail { get; set; }
        public virtual DbSet<Biz_SlabValueDetail> Biz_SlabValueDetail { get; set; }
        public virtual DbSet<Biz_Stakeholder> Biz_Stakeholder { get; set; }
        public virtual DbSet<Biz_StakeholderBranch> Biz_StakeholderBranch { get; set; }
        public virtual DbSet<Biz_StakeholderSecurityGroup> Biz_StakeholderSecurityGroup { get; set; }
        public virtual DbSet<Biz_StakeholderType> Biz_StakeholderType { get; set; }
        public virtual DbSet<Biz_StakeholderTypeSecurityGroup> Biz_StakeholderTypeSecurityGroup { get; set; }
        public virtual DbSet<Biz_StakeholderTypeStakeholder> Biz_StakeholderTypeStakeholder { get; set; }
        public virtual DbSet<Biz_SubProductCategory> Biz_SubProductCategory { get; set; }
        public virtual DbSet<Biz_SystemModule> Biz_SystemModule { get; set; }
        public virtual DbSet<Biz_UnitOfMeasure> Biz_UnitOfMeasure { get; set; }
        public virtual DbSet<Biz_UnitOfMeasureType> Biz_UnitOfMeasureType { get; set; }
        public virtual DbSet<Biz_UserLog> Biz_UserLog { get; set; }
    }
}
